-- Buat database
CREATE DATABASE IF NOT EXISTS web_praktikum CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE web_praktikum;


-- Tabel users
CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;